// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class WaterColorTransparencyKeys
    {
        public static readonly ValueParameterKey<Color3> WaterColor = ParameterKeys.NewValue<Color3>(new Color3(1.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Color3> FresnelColor = ParameterKeys.NewValue<Color3>(new Color3(1.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<float> BeersLawFactor = ParameterKeys.NewValue<float>(0.15f);
        public static readonly ValueParameterKey<float> DepthOffset = ParameterKeys.NewValue<float>(0.05f);
        public static readonly ValueParameterKey<bool> IsWaterDistortionEnabled = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<float> WaterDistortionScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<bool> IsWaterEdgeEnabled = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<Color3> WaterEdgeColor = ParameterKeys.NewValue<Color3>(new Color3(1.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<float> WaterEdgeDepthDiffThreshold = ParameterKeys.NewValue<float>(0.1f);
    }
}
